# Generated by Django 5.2.7 on 2026-03-10 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_category_blog_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.RemoveField(
            model_name='news',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_breaking',
        ),
        migrations.RemoveField(
            model_name='news',
            name='location',
        ),
        migrations.RemoveField(
            model_name='news',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.RemoveField(
            model_name='research',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='research',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='research',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='research',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='research',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='research',
            name='views',
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AddField(
            model_name='research',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.author'),
        ),
        migrations.AddField(
            model_name='research',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='research_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='research',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
