# Generated by Django 5.2.7 on 2026-03-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_blog_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='research',
            name='author',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='research',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='research',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(default=True, upload_to='research_images/'),
        ),
        migrations.AddField(
            model_name='research',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='research_by',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='research',
            name='short_description',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='research',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
