# Generated by Django 5.2.7 on 2026-03-12 18:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_blog_author_remove_research_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
