# Generated by Django 5.2.7 on 2026-03-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_research_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
