# Generated by Django 5.2.7 on 2026-03-12 18:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_research_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField()),
                ('written_by', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('content', tinymce.models.HTMLField()),
                ('date_of_publish', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_of_publish'],
            },
        ),
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(upload_to='research_images/'),
        ),
        migrations.AlterField(
            model_name='research',
            name='research_by',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='research',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
