# Generated by Django 5.2.7 on 2026-03-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
