# Generated by Django 5.2.7 on 2026-03-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='facebook',
            field=models.URLField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='twitter',
            field=models.URLField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='whatsapp',
            field=models.URLField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(blank=True, default=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='sources',
            field=models.CharField(max_length=255),
        ),
    ]
