# Generated by Django 5.2.7 on 2026-03-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_aboutus_facebook_aboutus_twitter_aboutus_whatsapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='insta',
            field=models.URLField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='facebook',
            field=models.URLField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='twitter',
            field=models.URLField(default=True),
        ),
    ]
