# Generated by Django 5.2.7 on 2026-03-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_aboutus_whatsapp_aboutus_insta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
