# Generated by Django 5.2.7 on 2026-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_aboutus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='company',
            field=models.URLField(default=True, null=True),
        ),
    ]
