# Generated by Django 5.2.7 on 2026-03-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_aboutus_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examupdate',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
