# Generated by Django 5.2.7 on 2026-03-16 08:03

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_aboutus_active_blog_active_contactmessage_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='active',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='company',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='facebook',
            field=models.URLField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='insta',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='twitter',
            field=models.URLField(blank=True, default=True),
        ),
    ]
