# Generated by Django 5.2.7 on 2026-03-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_aboutus_short_description_alter_aboutus_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Active_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=False)),
                ('post', models.BooleanField(default=False)),
                ('reasearch', models.BooleanField(default=False)),
                ('news', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('blog', models.BooleanField(default=False)),
                ('about', models.BooleanField(default=False)),
                ('contanct', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
