# Generated by Django 5.2.7 on 2026-03-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_site_active_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_active_models',
            name='active',
        ),
    ]
