# Generated by Django 5.2.7 on 2026-03-21 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_site_active_models_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='exam_cat/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='site_active_models',
            name='about',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='site_active_models',
            name='blog',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='site_active_models',
            name='contanct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='site_active_models',
            name='home',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='site_active_models',
            name='news',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='site_active_models',
            name='post',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='site_active_models',
            name='reasearch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='site_active_models',
            name='update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examupdate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exam_cat'),
        ),
    ]
