# Generated by Django 5.2.7 on 2026-03-21 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_exam_sub_cat_examupdate_sub_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_sub_cat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exam_cat'),
        ),
    ]
