# Generated by Django 5.2.7 on 2026-06-07 15:03

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_exam_sub_cat_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(blank=True, max_length=300)),
                ('short_description', models.TextField()),
                ('content', tinymce.models.HTMLField()),
                ('total_vacancy', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('last_date', models.CharField(blank=True, max_length=100)),
                ('exam_date', models.CharField(blank=True, max_length=100)),
                ('apply_link', models.URLField(blank=True)),
                ('official_website', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='app.examcategory')),
            ],
        ),
    ]
