# Generated by Django 5.2.7 on 2026-06-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_admitcard_result_remove_exam_apply_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_sub_cat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='examupdate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='examupdate',
            name='Sub_cat',
        ),
        migrations.DeleteModel(
            name='Exam_cat',
        ),
        migrations.DeleteModel(
            name='Exam_Sub_cat',
        ),
        migrations.DeleteModel(
            name='ExamUpdate',
        ),
    ]
