# Generated by Django 5.2.7 on 2026-06-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_exam_sub_cat_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(default=1, upload_to='exam/'),
            preserve_default=False,
        ),
    ]
