# Generated by Django 5.2.7 on 2026-06-15 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_exam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
