# Generated by Django 5.2.7 on 2026-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_exam_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='publish',
            field=models.DateTimeField(),
        ),
    ]
